blank_issues_enabled: false
contact_links:
  - name: Lyrion Community Support Forum
    url: https://forums.lyrion.org/forum/user-forums/3rd-party-software
    about: Please use the Lyrion Community Forum for general questions, configuration help, and problems that are not specific bugs in this plugin.
